name: Build Android APK (auto-create project)

on:
  workflow_dispatch:
  push:
    paths:
      - 'dnd_character_sheet.zip'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip your source
        run: |
          rm -rf src
          unzip dnd_character_sheet.zip -d src
          ls -la src

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Create fresh Flutter app skeleton
        run: |
          rm -rf app
          flutter create app
          ls -la app

      - name: Move your code into the skeleton
        run: |
          # Переносим исходники и ресурсы
          rm -rf app/lib && mkdir -p app/lib
          cp -R src/lib/* app/lib/ || true

          mkdir -p app/assets
          if [ -d "src/assets" ]; then
            cp -R src/assets/* app/assets/
          fi

          # Заменяем pubspec.yaml на твой
          if [ -f "src/pubspec.yaml" ]; then
            rm -f app/pubspec.yaml
            cp src/pubspec.yaml app/pubspec.yaml
          fi

          echo "---- pubspec BEFORE patch ----"
          cat app/pubspec.yaml || true

          # ---- Правим environment:sdk на совместимый диапазон ----
          # Вариант 1: caret ^3.x.x -> '>=3.0.0 <4.0.0'
          sed -i -E "s/^([[:space:]]*sdk:[[:space:]]*)\\^[0-9.]+/\\1'>=3.0.0 <4.0.0'/" app/pubspec.yaml
          # Вариант 2: '>=2.x <3.0.0' -> '>=3.0.0 <4.0.0'
          sed -i -E "s/^([[:space:]]*sdk:[[:space:]]*)'>=2\\.[0-9.]+ <3\\.0\\.0'/\\1'>=3.0.0 <4.0.0'/" app/pubspec.yaml

          # ---- Гарантируем, что секция flutter: содержит assets ----
          # Если нет строки 'flutter:', добавим её в конец вместе с assets:
          if ! grep -qE '^flutter:' app/pubspec.yaml; then
            printf "\nflutter:\n  assets:\n    - assets/\n" >> app/pubspec.yaml
          else
            # Если есть flutter:, но нет assets:, аккуратно добавим
            if ! grep -qE '^[[:space:]]+assets:' app/pubspec.yaml; then
              # добавим под flutter:
              awk 'BEGIN{p=1}
                /^flutter:/ {print; print "  assets:\n    - assets/"; p=0; next}
                {print}
              ' app/pubspec.yaml > app/_tmp_pubspec.yaml && mv app/_tmp_pubspec.yaml app/pubspec.yaml
            fi
          fi

          echo "---- pubspec AFTER patch ----"
          cat app/pubspec.yaml || true

      - name: Flutter pub get
        working-directory: app
        run: flutter pub get

      - name: Build debug APK
        working-directory: app
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/app/outputs/flutter-apk/app-debug.apk
